FROM node:16-alpine as build

WORKDIR /devils-crm-backend

ARG NODE_ENV
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_HOST_UAT
ARG DB_DATABASE
ARG PORT
ARG JWT_SECRET
ARG JWT_EXPIRARGES_IN
ARG SENDGRID_API_KEY
ARG SENDER_EMAIL

ENV PATH /devils-crm-backend/node_modules/.bin:$PATH
ENV NODE_ENV=${NODE_ENV}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_HOST_UAT=${DB_HOST_UAT}
ENV DB_DATABASE=${DB_DATABASE}
ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV SENDER_EMAIL=${SENDER_EMAIL}

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install --quiet

COPY . ./

RUN npm run build --quiet

EXPOSE 3000

CMD npm start

